#!/usr/bin/env python

import unittest
import math
import dor
import os
import zmq
import threading
import subprocess
import json
import hubmonitools

# Dummy LiveControl ZMQ listener on localhost
class ServerThread(threading.Thread):
    def __init__(self, port):
        threading.Thread.__init__(self)
        self.context = zmq.Context()
        self.socket = self.context.socket(zmq.PULL)
        self.socket.bind("tcp://*:%s" % port)
        self.poller = zmq.Poller()
        self.poller.register(self.socket, zmq.POLLIN)
        self.keepAlive = True
        self.data = []
        
    def run(self):
        while self.keepAlive:            
            socks = dict(self.poller.poll(100)) 
            if self.socket in socks and socks[self.socket] == zmq.POLLIN:
                msg = self.socket.recv()
                self.data.append(json.loads(msg))

# HubMoni tests
class HubMoniTests(unittest.TestCase):
    CONFIGFILE = os.path.dirname(os.path.abspath(__file__))+"/hubmoni.config"
    BINDIR = os.path.dirname(os.path.abspath(__file__))+"/../bin"
    
    @classmethod
    def setUpClass(cls):
        # The setup here starts the dummy listener thread and
        # actually runs hubmoni.  The individual tests just check
        # the data generated by this single execution, to save time.        
        super(HubMoniTests, cls).setUpClass()
        cls.config = hubmonitools.HubMoniConfig(HubMoniTests.CONFIGFILE)
        server = ServerThread(cls.config.ZMQ_PORT)
        server.start()

        cmd = [HubMoniTests.BINDIR+"/hubmoni.py",
               "-c", HubMoniTests.CONFIGFILE, "-s"]
        p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        if p:
            stdout, stderr = p.communicate()
        cls.data = server.data
        server.keepAlive = False
        
    def setUp(self):
        self.data = HubMoniTests.data
        self.config = HubMoniTests.config
        
    def testHubMoniAlert(self):
        # The moniDOMs tests validate the main content
        # Here we just check that they are sent via ZMQ and
        # some of the configuration options
        alerts = [a for a in self.data if a["varname"] == "alert"]
        self.failUnless(len(alerts) == 1)
        a = alerts[0]
        # The test config file should override this
        self.failUnless((a["value"]["notifies"][0]["receiver"] == "bogus@bogus.com") and
                        (a["value"]["pages"]) and
                        (a["service"] == "hubmoni"))

    def testHubMoniRecord(self):
        # Check that we received the correct number of records
        # moniDOMs tests validate the content
        pwrstat_recs = [r for r in self.data if "pwrstat" in r["varname"]]
        comstat_recs = [r for r in self.data if "comstat" in r["varname"]]
        cabling_recs = [r for r in self.data if "cabling" in r["varname"]]
        self.failUnless((len(pwrstat_recs) == (self.config.MAX_SIMLOOP_CNT*2)) and
                        (len(comstat_recs) == (self.config.MAX_SIMLOOP_CNT-1)*4) and
                        (len(cabling_recs) == (self.config.MAX_SIMLOOP_CNT)))



